import axios from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

interface CheckoutDetails {
    id: string
    symbol: string
    rate_usd: string
    address: string
    amount: string
    value: string
    qrcode: string
    href: string
    check: string
    memo: string
    username: string
}

interface Props {
    checkoutDetails: CheckoutDetails
}
 
const CheckoutPage: NextPage<Props> = ({checkoutDetails}) => {
    const {username, amount, value, memo, qrcode, href} = checkoutDetails
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-r from-indigo-200 via-red-200 to-yellow-100 py-6 flex flex-col justify-center relative overflow-hidden sm:py-12">
        <div className="relative px-6 pt-10 pb-8 bg-white shadow-xl ring-1 ring-gray-900/5 sm:max-w-lg sm:mx-auto sm:rounded-lg sm:px-10">
          <div className="max-w-md mx-auto">
            <div className="divide-y divide-gray-300/50">
              <div className="font-semibold text-center">
                <h1 className="">{memo}</h1>
                <p className="text-4xl py-2">${value}</p>
                <p className="font-light mb-8">{amount} XNO</p>
              </div>

              <div className="py-8 text-base leading-7 space-y-6 text-center">    
                <p className="font-thin">You are paying to <span className="font-normal">{username}</span>.<br/>Scan or click on the QR to checkout</p>
                    <Link href={href}>
                        <a>
                            <img className="w-full rounded-2xl shadow-xl hover:shadow-2xl cursor-pointer" src={qrcode}/>
                        </a>
                    </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default CheckoutPage


export  const getServerSideProps: GetServerSideProps = async ({query}) => {
    const { username, cost, memo } = query

    const res = await axios.get(`https://nano.to/${username}?request=${cost}&memo=${memo}`)
    console.log("=== rest", res.data)
    
    return {
      props: {
          checkoutDetails: {
              ...res.data,
              username
          }
      }, // will be passed to the page component as props
    }
  }