import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>XNO Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-r from-indigo-200 via-red-200 to-yellow-100 py-6 flex flex-col justify-center relative overflow-hidden sm:py-12">
        <div className="relative">
          <div className="max-w-md mx-auto">
              <div className="font-semibold text-center">
                <h1 className="text-4xl">Generate your <br />XNO Checkout url</h1>
              </div>

              {/* <div className="py-8 text-base leading-7 space-y-6 text-center">
                <input type="text" placeholder="your username" />
                <input type="text" placeholder="item" />
                <input type="number" placeholder="price" />
                <button>Generate</button>
              </div> */}
            </div>
        </div>
      </main>
    </div>
  )
}

export default Home